### ISSUE TITLE
Error while processing colorscheme

### ISSUE THREAD

**Issue by b3z** [UTFeight/tranquil-nvim#1]
To fix that you might want to define a light theme :)

![image](https://user-images.githubusercontent.com/47346598/218988072-e01749e4-d7ea-4ef9-990f-5fad55109b2e.png)

**Comment by KoBruhh** [comment]
hello. I don't think you are using neovim. As it seems that you are using vim instead.

**Comment by orhnk** [comment]
Could you try:
**Temporary**
```vim
:set background=dark
```
**Permanent**
-> add this to your .vimrc or init.vim
